name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        
      - name: Install Netlify
        run: pnpm install netlify-cli -g
      
      
      - name: Build project
        run: pnpm run build
        
      - name: Test
        run: pnpm run test:coverage

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

#      - name: Deploy to Netlify
#        id: netlify_deploy
#        run: |
#          netlify deploy \
#            --site ${{ secrets.NETLIFY_SITE_ID }} \
#            --auth ${{ secrets.NETLIFY_API_TOKEN }}